/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Mon Mar 13 22:17:41 2017. */

#include "comm_packet.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CommandPacket_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, CommandPacket, NormalizedVoltage, NormalizedVoltage, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, CommandPacket, SecondCommand, NormalizedVoltage, 0),
    PB_LAST_FIELD
};

const pb_field_t TelemetryPacket_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, TelemetryPacket, Position, Position, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, TelemetryPacket, Velocity, Position, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, TelemetryPacket, NewTelemetry, Velocity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
