/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Thu Mar 23 15:11:28 2017. */

#ifndef PB_COMM_PACKET_PB_H_INCLUDED
#define PB_COMM_PACKET_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _IdValuePairFloat {
    char Id[15];
    bool has_Value;
    float Value;
/* @@protoc_insertion_point(struct:IdValuePairFloat) */
} IdValuePairFloat;

typedef struct _WayPoint {
    float Heading;
    float Distance;
    char Name[15];
/* @@protoc_insertion_point(struct:WayPoint) */
} WayPoint;

typedef struct _CommandPacket {
    bool has_WayPointCmd;
    WayPoint WayPointCmd;
    pb_size_t RoverCmds_count;
    IdValuePairFloat RoverCmds[5];
/* @@protoc_insertion_point(struct:CommandPacket) */
} CommandPacket;

typedef struct _TelemetryPacket {
    float MeasuredHeading;
    float MeasuredDistance;
    pb_size_t RoverStatus_count;
    IdValuePairFloat RoverStatus[5];
/* @@protoc_insertion_point(struct:TelemetryPacket) */
} TelemetryPacket;

/* Default values for struct fields */

/* Initializer values for message structs */
#define WayPoint_init_default                    {0, 0, ""}
#define IdValuePairFloat_init_default            {"", false, 0}
#define CommandPacket_init_default               {false, WayPoint_init_default, 0, {IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default}}
#define TelemetryPacket_init_default             {0, 0, 0, {IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default, IdValuePairFloat_init_default}}
#define WayPoint_init_zero                       {0, 0, ""}
#define IdValuePairFloat_init_zero               {"", false, 0}
#define CommandPacket_init_zero                  {false, WayPoint_init_zero, 0, {IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero}}
#define TelemetryPacket_init_zero                {0, 0, 0, {IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero, IdValuePairFloat_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define IdValuePairFloat_Id_tag                  1
#define IdValuePairFloat_Value_tag               2
#define WayPoint_Heading_tag                     1
#define WayPoint_Distance_tag                    2
#define WayPoint_Name_tag                        3
#define CommandPacket_WayPointCmd_tag            1
#define CommandPacket_RoverCmds_tag              2
#define TelemetryPacket_MeasuredHeading_tag      1
#define TelemetryPacket_MeasuredDistance_tag     2
#define TelemetryPacket_RoverStatus_tag          3

/* Struct field encoding specification for nanopb */
extern const pb_field_t WayPoint_fields[4];
extern const pb_field_t IdValuePairFloat_fields[3];
extern const pb_field_t CommandPacket_fields[3];
extern const pb_field_t TelemetryPacket_fields[4];

/* Maximum encoded size of messages (where known) */
#define WayPoint_size                            27
#define IdValuePairFloat_size                    22
#define CommandPacket_size                       149
#define TelemetryPacket_size                     130

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMM_PACKET_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
