import re

def comment_remover(text):
    def replacer(match):
        s = match.group(0)
        if s.startswith('/'):
            return " "
        else:
            return s
    pattern = re.compile(
        r'//.*?$|/\*.*?\*/|\'(?:\\.|[^\\\'])*\'|"(?:\\.|[^\\"])*"',
        re.DOTALL | re.MULTILINE
    )
    return re.sub(pattern, replacer, text)

constants = {}
with open('../Arduino/ProtoWi/CmdResponseDefinitions.h') as infile:
    lines = infile.read()
    lines_no_comments = comment_remover(lines)
    res = re.findall(r'#define\s+(\w+)\s+(\w+)', lines_no_comments)
    for name, value in res:
        constants[name] = value

with open('../Python/CmdResponseDefinitions.py', 'w') as outfile:
	outfile.write("# Cmd IDs and Response IDs. Autogenerated from header file \n")
	outfile.write("# in CmdResponseDefinitions.h \n")
	outfile.write("\n")
	for constant in constants.keys():
		outfile.write(constant + " = " + str(constants[constant])+"\n")
	outfile.write("\n")
	outfile.write("\n")
