# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm_packet.proto',
  package='',
  serialized_pb=_b('\n\x11\x63omm_packet.proto\"A\n\rCommandPacket\x12\x19\n\x11NormalizedVoltage\x18\x01 \x02(\x02\x12\x15\n\rSecondCommand\x18\x02 \x02(\x02\"K\n\x0fTelemetryPacket\x12\x10\n\x08Position\x18\x01 \x02(\x02\x12\x10\n\x08Velocity\x18\x02 \x02(\x02\x12\x14\n\x0cNewTelemetry\x18\x03 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMANDPACKET = _descriptor.Descriptor(
  name='CommandPacket',
  full_name='CommandPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NormalizedVoltage', full_name='CommandPacket.NormalizedVoltage', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecondCommand', full_name='CommandPacket.SecondCommand', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=86,
)


_TELEMETRYPACKET = _descriptor.Descriptor(
  name='TelemetryPacket',
  full_name='TelemetryPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Position', full_name='TelemetryPacket.Position', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Velocity', full_name='TelemetryPacket.Velocity', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NewTelemetry', full_name='TelemetryPacket.NewTelemetry', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['CommandPacket'] = _COMMANDPACKET
DESCRIPTOR.message_types_by_name['TelemetryPacket'] = _TELEMETRYPACKET

CommandPacket = _reflection.GeneratedProtocolMessageType('CommandPacket', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDPACKET,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:CommandPacket)
  ))
_sym_db.RegisterMessage(CommandPacket)

TelemetryPacket = _reflection.GeneratedProtocolMessageType('TelemetryPacket', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYPACKET,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:TelemetryPacket)
  ))
_sym_db.RegisterMessage(TelemetryPacket)


# @@protoc_insertion_point(module_scope)
